# python
brew "pyenv"
brew "pyenv-virtualenvwrapper"
brew "pipx"
brew "automake"
brew "libtool"

# cli tools
brew "fzf"
brew "wget"
brew "jq"


# dev tools
brew "shellcheck"
cask "beyond-compare"
brew "duti"

# for vscode symbol generation
brew "ctags"
brew "nbdime"
brew "pandoc"


# node
brew "node"
brew "yarn"
brew "Schniz/tap/fnm"

# install mac apps
cask "iterm2"
cask "slack" unless system "[[ -d '/Applications/Slack.app' ]]"
cask "visual-studio-code"

