name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: remove packages already on runner that will be installed by install.sh
        run: |
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt
      - name: install.sh
        run: ./install.sh
