name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: remove packages already on runner that will be installed by install.sh
        run: |
          rm '/usr/local/bin/aws'
          brew unlink go@1.15
      - name: install.sh
        run: ./install.sh
