name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # remove the packages we install that are already in the environment
      # see https://github.com/actions/virtual-environments
      - name: remove existing packages
        run: |
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt
          rm "$HOME/.gitconfig"
      - name: install.sh
        run: ./install.sh

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
